# Assignment 0
**Instrunctions for the assignment** \\

*   Open Google Colab: Begin by launching Google Colab and creating a new Python notebook.
*   Read Comments Carefully: Pay close attention to the comments provided within the codeblocks.


*   Code Block Completion: Fill in the codeblocks as per the instructions given in the comments.
*   Avoid Copying: Ensure that you understand the concepts and refrain from directly copying code from external sources.


*   Execute Codeblocks: Verify that each codeblock runs without errors by executing them.
*   Save and Submit: Once you've completed the assignment, save your notebook and follow the submission guidelines provided.










**Notes:**

Encouragement: Take your time to understand the concepts behind each codeblock. This assignment aims to strengthen your Python programming skills. \\
Good Luck! : If you have any questions or require clarification on any aspect of the instructions, feel free to ask. \\
 \\

Best wishes for your assignment! These instructions are crafted to provide clarity and guidance as you work through the tasks in Google Colab.









## Getting Started
Solving these exercises will help make you a better programmer. Solve them in order, because each solution builds scaffolding, working code, and knowledge you can use on future problems. Read the directions carefully, and have fun!



*   To save your work to your Google Drive, go to File then "Save Copy in Drive".
*   Your own work will now appear in your Google Drive account!
*   Work on this copy as directed

## Basic Python Exercises

1. Create a new list from two list \\
list1 = [10, 20, 25, 30, 35] \\
list2 = [40, 45, 60, 75, 90]

In [40]:
# Note- Question does not specify a particular operation to be done in order to craete a new list from list1 and list2. Intuitionally, I have merged the two lists.
list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]
LIST= []
LIST.append(list1)
LIST.append(list2)
print(LIST)


[[10, 20, 25, 30, 35], [40, 45, 60, 75, 90]]


2. Print multiplication table from 1 to 10

In [41]:
import numpy as np

nums = np.linspace(1, 10, 10,dtype=int)

for i in nums:
    print(f"Multiplication table of {i}")
    for j in nums:
        print(f"{i} x {j} = {i*j}")
    print()

Multiplication table of 1
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10

Multiplication table of 2
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

Multiplication table of 3
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

Multiplication table of 4
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

Multiplication table of 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

Multiplication table of 6
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

Multiplication table of 7
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

Multiplication table of 8
8 x 1 = 8
8 x 2 = 16
8 x 3 = 

3. Print a downward Half-Pyramid Pattern

0 0 0 0 0   
0 0 0 0 <br>
0 0 0 <br>
0 0 <br>
0

In [42]:
for i in range(5,0,-1):
  for j in range(0,i):
    print('0', end=" ")
  print()

0 0 0 0 0 
0 0 0 0 
0 0 0 
0 0 
0 


 4. Given the following assignment of the vegetables list, add "tomato" to the end of the list and sort them in alphabetical order.\
vegetables = ["eggplant", "broccoli", "carrot","cauliflower", "zucchini"]

In [43]:
vegetables = ["eggplant", "broccoli", "carrot","cauliflower", "zucchini"]
vegetables.append("tomato")
vegetables.sort()
print(vegetables)

['broccoli', 'carrot', 'cauliflower', 'eggplant', 'tomato', 'zucchini']


5. Write a function definition named is_odd that takes in a number and returns True or False if that number is odd.

In [44]:
def is_odd(num):
    return num % 2 != 0

6. Write a function definition named mode that takes in sequence of numbers and returns the most commonly occuring value

In [45]:
def mode(seq):
    max_count = 0
    mode_value = None

    for num in seq:
        count = seq.count(num)
        if count > max_count:
            max_count = count
            mode_value = num

    return mode_value

## Numpy Exercises

Exercise 1: Create a 4X2 integer array and Prints its attributes \\
**Note:** The element must be a type of unsigned int16. \\
And print the following Attributes: –



1.   The shape of an array.
2.   Array dimensions.
3.   The Length of each element of the array in bytes.







In [46]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]], dtype=np.uint16)

print("\nShape of array:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Length of each element in bytes:", arr.itemsize)


Shape of array: (4, 2)
Number of dimensions: 2
Length of each element in bytes: 2


Exercise 2: Following is the provided numPy array. Return array of items by taking the third column from all rows \\
sampleArray = numpy.array ( [ [ 11 ,22, 33 ], [ 44, 55, 66 ], [ 77, 88, 99 ] ] )

In [47]:
import numpy as np

sampleArray = np.array([[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]])


result = sampleArray[:, 2]

print(result)

[33 66 99]


Exercise 3: Sort following NumPy array \\
Case 1: Sort array by the second row \\
Case 2: Sort the array by the second column

In [48]:
import numpy as np

arr = np.array([[11, 22, 33],
                [44, 55, 66],
                [77, 88, 99]])
sorted_second_row = np.sort(arr[1])
print(sorted_second_row)

sorted_second_column = np.sort(arr[:, 1])
print(sorted_second_column)

[44 55 66]
[22 55 88]


## Pandas Exercises
In this exercise, we are using Automobile Dataset for data analysis. This Dataset has different characteristics of an auto such as body-style, wheel-base, engine-type, price, mileage, horsepower, etc. \\
https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv

Exercise 1: From the given dataset print the first and last five rows.

In [49]:
import pandas as pd

df = pd.read_csv("https://www.google.com/url?q=https%3A%2F%2Fpynative.com%2Fwp-content%2Fuploads%2F2019%2F01%2FAutomobile_data.csv")

print(df.head())

print(df.tail())

Empty DataFrame
Columns: [<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"><title>Redirect Notice</title><style>body, div, a{font-family:sans-serif}body{background-color:#fff;margin-top:3px}div{color:#1f1f1f}a:link{color:#681da8}a:visited{color:#681da8}a:active{color:#ea4335}div.mymGo{border-top:1px solid #dadce0;border-bottom:1px solid #dadce0;background:#ecedee;margin-top:1em;width:100%}div.aXgaGb{padding:0.5em 0;margin-left:10px}div.fTk7vd{margin-left:35px;margin-top:35px}</style></head><body><div class="mymGo"><div class="aXgaGb"><font style="font-size:larger"><b>Redirect Notice</b></font></div></div><div class="fTk7vd">&nbsp;The previous page is sending you to <a href="https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv">https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv</a>.<br><br>&nbsp;If you do not want to visit that page,  you can <a href="#" id="tsuid_aYU9aefaDY3gkPIP14WEiQg_1">return to the previo

Exercise 2: Replace all column values which contain ?, n.a, or NaN with suitable values and print the updated dataset.:

In [61]:
import pandas as pd
import numpy as np
df = pd.read_csv("https://www.google.com/url?q=https%3A%2F%2Fpynative.com%2Fwp-content%2Fuploads%2F2019%2F01%2FAutomobile_data.csv")

df.replace(['?', 'n.a'], np.nan, inplace=True)

df.fillna(0, inplace=True)

print(df)

Empty DataFrame
Columns: [<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"><title>Redirect Notice</title><style>body, div, a{font-family:sans-serif}body{background-color:#fff;margin-top:3px}div{color:#1f1f1f}a:link{color:#681da8}a:visited{color:#681da8}a:active{color:#ea4335}div.mymGo{border-top:1px solid #dadce0;border-bottom:1px solid #dadce0;background:#ecedee;margin-top:1em;width:100%}div.aXgaGb{padding:0.5em 0;margin-left:10px}div.fTk7vd{margin-left:35px;margin-top:35px}</style></head><body><div class="mymGo"><div class="aXgaGb"><font style="font-size:larger"><b>Redirect Notice</b></font></div></div><div class="fTk7vd">&nbsp;The previous page is sending you to <a href="https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv">https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv</a>.<br><br>&nbsp;If you do not want to visit that page,  you can <a href="#" id="tsuid_N4c9aYCBNc3hkPIPr5WqiQo_1">return to the previo


Exercise 5: Count total cars per company and print them




In [60]:
import pandas as pd

df = pd.read_csv("https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv")

cars_per_company = df['company'].value_counts()

print(cars_per_company)

HTTPError: HTTP Error 403: Forbidden

## Matplotlib Exercises

Use the following CSV file for this exercise. Read this file using Pandas or NumPy or using in-built matplotlib function. \\
https://pynative.com/wp-content/uploads/2019/01/company_sales_data.csv

Exercise 1: Read Total profit of all months and show it using a line plot \\
Total profit data provided for each month. Generated line plot must include the following properties: –

X label name = Month Number \\
Y label name = Total profit \\




In [58]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("https://pynative.com/wp-content/uploads/2019/01/company_sales_data.csv")



plt.plot(range(1, 13), df['total_profit'], marker='o', color='green')
plt.xlabel("Month Number")
plt.ylabel("Total Profit")
plt.title("Total Profit of All Months")
plt.grid(True)
plt.show()

HTTPError: HTTP Error 403: Forbidden

Exercise : Read face cream and facewash product sales data and show it using the bar chart \\
The bar chart should display the number of units sold per month for each product. \\
Add a separate bar for each product in the same chart.

In [59]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("https://pynative.com/wp-content/uploads/2019/01/company_sales_data.csv")

plt.bar(range(1, 13), data['facecream'], label='Face Cream')
plt.bar(range(1, 13), data['facewash'], bottom=data['facecream'], label='Face Wash')


plt.xlabel("Month")
plt.ylabel("Units Sold")
plt.title("Face Cream & Face Wash Sales")
plt.legend()

plt.show()

HTTPError: HTTP Error 403: Forbidden